version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    depends_on:
      - backend
    working_dir: /frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  complier:
    build:
      context: ./codeX
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
